# Generated by Django 6.1 on 2026-09-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_room_price_non_negative"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("finish_date"))),
                name="booking_dates_valid",
            ),
        ),
    ]
